interface button {
    use shared.{element};
    use length.{length};
    use padding.{padding};
    use callbacks.{callback-id};

    resource button {
        constructor(content: element);
        on-press: func(msg: callback-id);
        width: func(w: length);
        height: func(h: length);
        padding: func(p: padding);
        clip: func(clip: bool);
        into-element: static func(widget: button) -> element;
    }
}
