interface checkbox {
    use shared.{pixels, element};
    use length.{length};
    use text.{line-height, shaping, wrapping};
    use callbacks.{callback-id};

    /// A box that can be checked.
    resource checkbox {
        constructor(is-checked: bool);
        label: func(label: string);
        on-toggle: func(mapper: callback-id);
        size: func(s: pixels);
        width: func(w: length);
        spacing: func(s: pixels);
        text-size: func(s: pixels);
        text-line-height: func(lh: line-height);
        text-wrapping: func(w: wrapping);
        text-shaping: func(s: shaping);
        into-element: static func(widget: checkbox) -> element;
    }
}
