interface column {
    use shared.{pixels, element};
    use length.{length};
    use padding.{padding};
    use alignment.{horizontal};

    resource column {
        constructor();
        push: func(child: element);
        spacing: func(amount: pixels);
        padding: func(p: padding);
        width: func(w: length);
        height: func(h: length);
        max-width: func(max: pixels);
        align-x: func(align: horizontal);
        clip: func(clip: bool);
        into-element: static func(widget: column) -> element;
    }
}
