interface combo-box {
    use shared.{element};
    use text.{line-height};
    use length.{length};
    use padding.{padding};
    use callbacks.{callback-id};

    /// A widget allowing selection from a list of options.
    resource combo-box {
        constructor(options: list<string>, placeholder: string, selected: option<string>, on-selected: callback-id);
        on-input: func(mapper: callback-id);
        on-option-hovered: func(mapper: callback-id);
        on-open: func(msg: callback-id);
        on-close: func(msg: callback-id);
        padding: func(p: padding);
        size: func(s: f32);
        line-height: func(lh: line-height);
        width: func(w: length);
        into-element: static func(widget: combo-box) -> element;
    }
}
