interface container {
    use shared.{pixels, element};
    use length.{length};
    use padding.{padding};
    use alignment.{horizontal, vertical};

    resource container {
        constructor(content: element);
        padding: func(p: padding);
        width: func(w: length);
        height: func(h: length);
        max-width: func(max: pixels);
        max-height: func(max: pixels);
        center-x: func(w: length);
        center-y: func(h: length);
        center: func(l: length);
        align-left: func(w: length);
        align-right: func(w: length);
        align-top: func(h: length);
        align-bottom: func(h: length);
        align-x: func(align: horizontal);
        align-y: func(align: vertical);
        clip: func(clip: bool);
        into-element: static func(widget: container) -> element;
    }
}
