interface float {
    use shared.{element};

    /// A translation applied to content.
    record translation {
        /// Horizontal offset.
        x: f32,
        /// Vertical offset.
        y: f32,
    }

    /// Displays floating content on top of the application.
    resource float {
        constructor(content: element);
        scale: func(s: f32);
        translation: func(t: translation);
        into-element: static func(widget: float) -> element;
    }
}
