interface grid {
    use shared.{pixels, element};

    /// A container that arranges its contents in a grid.
    resource grid {
        constructor();
        push: func(child: element);
        spacing: func(amount: pixels);
        width: func(w: pixels);
        height: func(h: pixels);
        columns: func(columns: u64);
        fluid: func(amount: pixels);
        into-element: static func(widget: grid) -> element;
    }
}
