interface image {
    use shared.{element, rotation, content-fit, filter-method};
    use length.{length};

    /// A frame that displays an image.
    resource image {
        constructor(handle: string);
        width: func(w: length);
        height: func(h: length);
        expand: func(expand: bool);
        content-fit: func(fit: content-fit);
        filter-method: func(method: filter-method);
        rotation: func(r: rotation);
        opacity: func(o: f32);
        scale: func(s: f32);
        into-element: static func(widget: image) -> element;
    }
}
