interface keyed {
    use shared.{pixels, element};
    use length.{length};
    use padding.{padding};
    use alignment.{alignment};

    resource keyed-column {
        constructor();
        push: func(key: u64, child: element);
        spacing: func(amount: pixels);
        padding: func(p: padding);
        width: func(w: length);
        height: func(h: length);
        max-width: func(amount: pixels);
        align-items: func(align: alignment);
        into-element: static func(widget: keyed-column) -> element;
    }
}
