interface pick-list {
    use shared.{pixels, element};
    use length.{length};
    use text.{line-height, shaping};
    use padding.{padding};
    use callbacks.{callback-id};

    /// A widget for selecting a value from a set of options.
    resource pick-list {
        constructor(options: list<string>, selected: option<string>, on-select: callback-id);
        placeholder: func(text: string);
        width: func(w: length);
        padding: func(p: padding);
        text-size: func(s: pixels);
        text-line-height: func(lh: line-height);
        text-shaping: func(s: shaping);
        on-open: func(msg: callback-id);
        on-close: func(msg: callback-id);
        into-element: static func(widget: pick-list) -> element;
    }
}
