interface progress-bar {
    use shared.{element};
    use length.{length};

    /// A bar that displays progress.
    resource progress-bar {
        constructor(range-start: f32, range-end: f32, value: f32);
        length: func(l: length);
        girth: func(g: length);
        vertical: func(v: bool);
        into-element: static func(widget: progress-bar) -> element;
    }
}
