interface radio {
    use shared.{pixels, element};
    use length.{length};
    use text.{line-height, shaping, wrapping};
    use callbacks.{callback-id};

    /// A circular button representing an alternative.
    resource radio {
        constructor(label: string, is-selected: bool, msg: callback-id);
        size: func(s: pixels);
        width: func(w: length);
        spacing: func(s: pixels);
        text-size: func(s: pixels);
        text-line-height: func(lh: line-height);
        text-wrapping: func(w: wrapping);
        text-shaping: func(s: shaping);
        into-element: static func(widget: radio) -> element;
    }
}
