interface row {
    use shared.{pixels, element};
    use length.{length};
    use padding.{padding};
    use alignment.{vertical};

    resource row {
        constructor();
        push: func(child: element);
        spacing: func(amount: pixels);
        padding: func(p: padding);
        width: func(w: length);
        height: func(h: length);
        align-y: func(align: vertical);
        clip: func(clip: bool);
        wrap: func(wrap: bool);
        into-element: static func(widget: row) -> element;
    }
}
