interface scrollable {
    use shared.{pixels, element};
    use length.{length};
    use callbacks.{callback-id};

    /// The anchor of the scroller of a scrollable relative to its viewport.
    enum anchor {
        start,
        end,
    }

    record scrollbar {
        width: option<pixels>,
        margin: option<pixels>,
        scroller-width: option<pixels>,
        anchor: option<anchor>,
        spacing: option<pixels>,
    }

    variant direction {
        vertical(scrollbar),
        horizontal(scrollbar),
        both(tuple<scrollbar, scrollbar>),
    }

    resource scrollable {
        constructor(content: element);
        width: func(w: length);
        height: func(h: length);
        direction: func(d: direction);
        on-scroll: func(mapper: callback-id);
        into-element: static func(widget: scrollable) -> element;
    }
}
