interface shared {
    type pixels = f32;

    /// A color in the sRGB color space.
    record color {
        /// Red component, 0.0 - 1.0
        r: f32,
        /// Green component, 0.0 - 1.0
        g: f32,
        /// Blue component, 0.0 - 1.0
        b: f32,
        /// Alpha component, 0.0 - 1.0
        a: f32,
    }

    enum content-fit {
        contain,
        cover,
        fill,
        none,
        scale-down
    }

    enum filter-method {
        linear,
        nearest,
    }

    variant rotation {
        floating(f32),
        solid(f32),
    }

}
