interface shared {
    type pixels = f32;
    /// The base element resource for UI widgets.
    /// Note: The dummy function is required for jco componentize to generate the class.
    /// See: https://github.com/bytecodealliance/ComponentizeJS/issues/221
    resource element {
        /// Dummy function to trigger class generation in jco componentize.
        noop: func();
        /// Wraps the element with a debug overlay of the given color.
        explain: func(color: color) -> element;
    }

    /// A color in the sRGB color space.
    record color {
        /// Red component, 0.0 - 1.0
        r: f32,
        /// Green component, 0.0 - 1.0
        g: f32,
        /// Blue component, 0.0 - 1.0
        b: f32,
        /// Alpha component, 0.0 - 1.0
        a: f32,
    }

    enum content-fit {
        contain,
        cover,
        fill,
        none,
        scale-down
    }

    enum filter-method {
        linear,
        nearest,
    }

    variant rotation {
        floating(f32),
        solid(f32),
    }

}
