interface slider {
    use shared.{pixels, element};
    use length.{length};
    use callbacks.{callback-id};

    /// A horizontal bar for selecting a value from a range of floats.
    resource slider {
        constructor(range-start: f32, range-end: f32, value: f32, on-change: callback-id);
        default: func(v: f32);
        on-release: func(msg: callback-id);
        width: func(w: length);
        height: func(h: pixels);
        step: func(s: f32);
        shift-step: func(s: f32);
        into-element: static func(widget: slider) -> element;
    }
}
