interface space {
    use shared.{element};
    use length.{length};

    /// An amount of empty space.
    resource space {
        constructor();
        width: func(w: length);
        height: func(h: length);
        into-element: static func(widget: space) -> element;
    }
}
