interface text {
    use length.{length};
    use alignment.{vertical};
    use shared.{pixels, color, element};

    variant text-alignment {
        default,
        left,
        center,
        right,
        justified,
    }

    variant line-height {
        relative(f32),
        absolute(pixels),
    }

    enum shaping {
        basic,
        advanced,
        auto,
    }

    enum wrapping {
        none,
        word,
        glyph,
        word-or-glyph,
    }

    resource text {
        constructor(content: string);
        size: func(s: f32);
        line-height: func(lh: line-height);
        width: func(w: length);
        height: func(h: length);
        center: func();
        align-x: func(align: text-alignment);
        align-y: func(align: vertical);
        color: func(c: color);
        into-element: static func(widget: text) -> element;
    }
}
