interface text-input {
    use shared.{pixels, element};
    use padding.{padding};
    use text.{line-height};
    use alignment.{horizontal};
    use length.{length};
    use callbacks.{callback-id};

    /// A field that can be filled with text.
    resource text-input {
        constructor(placeholder: string, value: string);
        secure: func(secure: bool);
        on-input: func(mapper: callback-id);
        on-submit: func(msg: callback-id);
        on-paste: func(mapper: callback-id);
        width: func(w: length);
        padding: func(p: padding);
        size: func(s: pixels);
        line-height: func(lh: line-height);
        align-x: func(a: horizontal);
        into-element: static func(widget: text-input) -> element;
    }
}
