interface toggler {
    use shared.{pixels, element};
    use text.{line-height, shaping, wrapping};
    use alignment.{horizontal};
    use length.{length};
    use callbacks.{callback-id};

    /// A widget representing a setting that can be toggled on or off.
    resource toggler {
        constructor(is-toggled: bool);
        label: func(label: string);
        on-toggle: func(mapper: callback-id);
        size: func(s: pixels);
        width: func(w: length);
        text-size: func(s: pixels);
        text-line-height: func(lh: line-height);
        text-alignment: func(a: horizontal);
        text-shaping: func(s: shaping);
        text-wrapping: func(w: wrapping);
        spacing: func(s: pixels);
        into-element: static func(widget: toggler) -> element;
    }
}
