interface tooltip {
    use shared.{pixels, element};

    enum position {
        top,
        bottom,
        left,
        right,
        follow-cursor,
    }

    resource tooltip {
        constructor(content: element, tooltip: element, position: position);
        gap: func(g: pixels);
        padding: func(p: pixels);
        snap-within-viewport: func(snap: bool);
        into-element: static func(widget: tooltip) -> element;
    }
}
