interface vertical-slider {
    use shared.{pixels, element};
    use length.{length};
    use callbacks.{callback-id};

    /// A vertical bar for selecting a value from a range of floats.
    resource vertical-slider {
        constructor(range-start: f32, range-end: f32, value: f32, on-change: callback-id);
        default: func(v: f32);
        on-release: func(msg: callback-id);
        width: func(w: pixels);
        height: func(h: length);
        step: func(s: f32);
        shift-step: func(s: f32);
        into-element: static func(widget: vertical-slider) -> element;
    }
}
