# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from .imports import message
from .imports import shared


class WitWorld(Protocol):
    @abstractmethod
    def update(self, message_id: int, message: message.Message) -> None:
        raise NotImplementedError

    @abstractmethod
    def view(self) -> shared.Element:
        """
        Exported function for creating a view
        """
        raise NotImplementedError
