interface length {
    /// The strategy used to fill space in a specific dimension.
    variant length {
        /// Fill all the remaining space
        fill,

        /// Fill a portion of the remaining space relative to other elements.
        ///
        /// Let's say we have two elements: one with `FillPortion(2)` and one with
        /// `FillPortion(3)`. The first will get 2 portions of the available space,
        /// while the second one would get 3.
        ///
        /// `Length::Fill` is equivalent to `Length::FillPortion(1)`.
        fill-portion(u16),

        /// Fill the least amount of space
        shrink,

        /// Fill a fixed amount of space
        fixed(f32),
    }
}