package iced:app@0.1.0;


world app {
    use shared.{element};
    use message.{message-id, message};

    import element;
    export message;

    export new: func() -> u64;

    export update: func(state: u64, message-id: message-id, message: message);

    /// Exported function for creating a view
    export view: func(state: u64) -> element;
}