[package]
name = "igloo"
version = "0.1.0"
edition.workspace = true
include = ["src/**/*", "wit/**/*", "README.md", "LICENSE"]

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
wasmtime = { workspace = true, features = ["async", "component-model-async"] }
wasmtime-wasi = { workspace = true }

iced.workspace = true
tracing.workspace = true
thiserror.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[lints]
workspace = true
