# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import message_types
from ..imports import shared


@dataclass
class MessageValue_Fixed:
    pass


@dataclass
class MessageValue_BoolValue:
    value: bool


@dataclass
class MessageValue_F32Value:
    value: float


@dataclass
class MessageValue_F64Value:
    value: float


@dataclass
class MessageValue_U64Value:
    value: int


@dataclass
class MessageValue_StringValue:
    value: str


@dataclass
class MessageValue_ViewportValue:
    value: message_types.Viewport


MessageValue = Union[MessageValue_Fixed, MessageValue_BoolValue, MessageValue_F32Value, MessageValue_F64Value, MessageValue_U64Value, MessageValue_StringValue, MessageValue_ViewportValue]
"""
The raw value produced by a widget interaction, if the callback it is being
dispatched to carries one. All-primitive, so it crosses the boundary as plain
data like `callback-id` does — no resource involved.
"""


class Application(Protocol):
    """
    A running plugin instance. Owns the plugin's state and every callback it has handed
    to the host for the current frame.
    """
    
    @abstractmethod
    def __init__(self) -> None:
        raise NotImplementedError

    @abstractmethod
    def view(self) -> shared.Element:
        raise NotImplementedError

    @abstractmethod
    def update(self, id: int, value: MessageValue) -> None:
        raise NotImplementedError


