# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class Vertical(Enum):
    """
    The vertical [`alignment`] of some resource.
    """

    TOP = 0
    CENTER = 1
    BOTTOM = 2


class Horizontal(Enum):
    """
    The horizontal [`alignment`] of some resource.
    """

    LEFT = 0
    CENTER = 1
    RIGHT = 2


class Alignment(Enum):
    """
    The alignment of some resource.
    """

    START = 0
    CENTER = 1
    END = 2
