# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import shared
from ..imports import padding
from ..imports import length
from ..imports import text

class ComboBox:
    """
    A widget allowing selection from a list of options.
    """
    
    def __init__(self, options: List[str], placeholder: str, selected: Optional[str], on_selected: int) -> None:
        raise NotImplementedError

    def on_input(self, mapper: int) -> None:
        raise NotImplementedError
    def on_option_hovered(self, mapper: int) -> None:
        raise NotImplementedError
    def on_open(self, msg: int) -> None:
        raise NotImplementedError
    def on_close(self, msg: int) -> None:
        raise NotImplementedError
    def padding(self, p: padding.Padding) -> None:
        raise NotImplementedError
    def size(self, s: float) -> None:
        raise NotImplementedError
    def line_height(self, lh: text.LineHeight) -> None:
        raise NotImplementedError
    def width(self, w: length.Length) -> None:
        raise NotImplementedError
    @classmethod
    def into_element(cls, widget: Self) -> shared.Element:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



