# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import padding
from ..imports import text
from ..imports import length

@dataclass
class ComboBox:
    """
    A widget allowing selection from a list of options.
    """
    options: List[str]
    placeholder: str
    selected: Optional[str]
    on_selected: int
    on_input: Optional[int]
    on_option_hovered: Optional[int]
    on_open: Optional[int]
    on_close: Optional[int]
    padding: Optional[padding.Padding]
    size: Optional[float]
    line_height: Optional[text.LineHeight]
    width: Optional[length.Length]


