# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import row
from ..imports import text_input
from ..imports import markdown
from ..imports import radio
from ..imports import slider
from ..imports import scrollable
from ..imports import checkbox
from ..imports import image
from ..imports import pick_list
from ..imports import pane_grid
from ..imports import shared
from ..imports import space
from ..imports import float
from ..imports import container
from ..imports import vertical_slider
from ..imports import keyed
from ..imports import text
from ..imports import grid
from ..imports import button
from ..imports import progress_bar
from ..imports import svg
from ..imports import rule
from ..imports import column
from ..imports import tooltip
from ..imports import toggler
from ..imports import table
from ..imports import combo_box


def explain(element: shared.Element, color: shared.Color) -> shared.Element:
    raise NotImplementedError


def text_to_element(text: text.Text) -> shared.Element:
    raise NotImplementedError


def column_to_element(column: column.Column) -> shared.Element:
    raise NotImplementedError


def button_to_element(button: button.Button) -> shared.Element:
    raise NotImplementedError


def row_to_element(row: row.Row) -> shared.Element:
    raise NotImplementedError


def container_to_element(container: container.Container) -> shared.Element:
    raise NotImplementedError


def tooltip_to_element(tooltip: tooltip.Tooltip) -> shared.Element:
    raise NotImplementedError


def rule_to_element(rule: rule.Rule) -> shared.Element:
    raise NotImplementedError


def checkbox_to_element(checkbox: checkbox.Checkbox) -> shared.Element:
    raise NotImplementedError


def combo_box_to_element(combo_box: combo_box.ComboBox) -> shared.Element:
    raise NotImplementedError


def float_to_element(float: float.Float) -> shared.Element:
    raise NotImplementedError


def grid_to_element(grid: grid.Grid) -> shared.Element:
    raise NotImplementedError


def progress_bar_to_element(progress_bar: progress_bar.ProgressBar) -> shared.Element:
    raise NotImplementedError


def toggler_to_element(toggler: toggler.Toggler) -> shared.Element:
    raise NotImplementedError


def radio_to_element(radio: radio.Radio) -> shared.Element:
    raise NotImplementedError


def image_to_element(image: image.Image) -> shared.Element:
    raise NotImplementedError


def keyed_column_to_element(keyed_column: keyed.KeyedColumn) -> shared.Element:
    raise NotImplementedError


def markdown_to_element(markdown: markdown.Markdown) -> shared.Element:
    raise NotImplementedError


def pane_grid_to_element(pane_grid: pane_grid.PaneGrid) -> shared.Element:
    raise NotImplementedError


def pick_list_to_element(pick_list: pick_list.PickList) -> shared.Element:
    raise NotImplementedError


def slider_to_element(slider: slider.Slider) -> shared.Element:
    raise NotImplementedError


def vertical_slider_to_element(vertical_slider: vertical_slider.VerticalSlider) -> shared.Element:
    raise NotImplementedError


def svg_to_element(svg: svg.Svg) -> shared.Element:
    raise NotImplementedError


def table_to_element(table: table.Table) -> shared.Element:
    raise NotImplementedError


def text_input_to_element(text_input: text_input.TextInput) -> shared.Element:
    """
    text-editor-to-element: func(text-editor: text-editor) -> element;
    """
    raise NotImplementedError


def space_to_element(space: space.Space) -> shared.Element:
    raise NotImplementedError


def scrollable_to_element(scrollable: scrollable.Scrollable) -> shared.Element:
    raise NotImplementedError
