# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import shared


@dataclass
class Translation:
    """
    A translation applied to content.
    """

    x: float
    y: float


@dataclass
class Float:
    """
    Displays floating content on top of the application.
    """

    content: shared.Element
    scale: Optional[float]
    translation: Optional[Translation]
