# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import shared

class Grid:
    """
    A container that arranges its contents in a grid.
    """
    
    def __init__(self) -> None:
        raise NotImplementedError

    def push(self, child: shared.Element) -> None:
        raise NotImplementedError
    def spacing(self, amount: float) -> None:
        raise NotImplementedError
    def width(self, w: float) -> None:
        raise NotImplementedError
    def height(self, h: float) -> None:
        raise NotImplementedError
    def columns(self, columns: int) -> None:
        raise NotImplementedError
    def fluid(self, amount: float) -> None:
        raise NotImplementedError
    @classmethod
    def into_element(cls, widget: Self) -> shared.Element:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



