# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import alignment
from ..imports import padding
from ..imports import length
from ..imports import shared

@dataclass
class KeyedColumn:
    """
    A container that keeps the state of its children using keys.
    """
    keys: List[int]
    children: List[shared.Element]
    spacing: Optional[float]
    padding: Optional[padding.Padding]
    width: Optional[length.Length]
    height: Optional[length.Length]
    max_width: Optional[float]
    align_items: Optional[alignment.Alignment]


