# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


@dataclass
class Length_Fill:
    pass


@dataclass
class Length_FillPortion:
    value: int


@dataclass
class Length_Shrink:
    pass


@dataclass
class Length_Fixed:
    value: float


Length = Union[Length_Fill, Length_FillPortion, Length_Shrink, Length_Fixed]
"""
The strategy used to fill space in a specific dimension.
"""
