# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


@dataclass
class Rectangle:
    x: float
    y: float
    width: float
    height: float

@dataclass
class AbsoluteOffset:
    x: float
    y: float

@dataclass
class RelativeOffset:
    x: float
    y: float

@dataclass
class Viewport:
    """
    The current Viewport of the Scrollable.
    """
    absolute_offset: AbsoluteOffset
    absolute_offset_reversed: AbsoluteOffset
    relative_offset: RelativeOffset
    bounds: Rectangle
    content_bounds: Rectangle


