# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import text
from ..imports import padding
from ..imports import shared
from ..imports import length

class PickList:
    """
    A widget for selecting a value from a set of options.
    """
    
    def __init__(self, options: List[str], selected: Optional[str], on_select: int) -> None:
        raise NotImplementedError

    def placeholder(self, text: str) -> None:
        raise NotImplementedError
    def width(self, w: length.Length) -> None:
        raise NotImplementedError
    def padding(self, p: padding.Padding) -> None:
        raise NotImplementedError
    def text_size(self, s: float) -> None:
        raise NotImplementedError
    def text_line_height(self, lh: text.LineHeight) -> None:
        raise NotImplementedError
    def text_shaping(self, s: text.Shaping) -> None:
        raise NotImplementedError
    def on_open(self, msg: int) -> None:
        raise NotImplementedError
    def on_close(self, msg: int) -> None:
        raise NotImplementedError
    @classmethod
    def into_element(cls, widget: Self) -> shared.Element:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



