# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import length
from ..imports import shared

class ProgressBar:
    """
    A bar that displays progress.
    """
    
    def __init__(self, range_start: float, range_end: float, value: float) -> None:
        raise NotImplementedError

    def length(self, l: length.Length) -> None:
        raise NotImplementedError
    def girth(self, g: length.Length) -> None:
        raise NotImplementedError
    def vertical(self, v: bool) -> None:
        raise NotImplementedError
    @classmethod
    def into_element(cls, widget: Self) -> shared.Element:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



