# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import length

@dataclass
class ProgressBar:
    """
    A bar that displays progress.
    """
    range_start: float
    range_end: float
    value: float
    length: Optional[length.Length]
    girth: Optional[length.Length]
    vertical: Optional[bool]


