# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import text
from ..imports import length

@dataclass
class Radio:
    """
    A circular button representing an alternative.
    """
    label: str
    is_selected: bool
    on_select: int
    size: Optional[float]
    width: Optional[length.Length]
    spacing: Optional[float]
    text_size: Optional[float]
    text_line_height: Optional[text.LineHeight]
    text_wrapping: Optional[text.Wrapping]
    text_shaping: Optional[text.Shaping]


