# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import shared
from ..imports import length


class Anchor(Enum):
    START = 0
    END = 1


@dataclass
class Scrollbar:
    width: Optional[float]
    margin: Optional[float]
    scroller_width: Optional[float]
    alignment: Optional[Anchor]
    spacing: Optional[float]


@dataclass
class Direction_Vertical:
    value: Scrollbar


@dataclass
class Direction_Horizontal:
    value: Scrollbar


@dataclass
class Direction_Both:
    value: Tuple[Scrollbar, Scrollbar]


Direction = Union[Direction_Vertical, Direction_Horizontal, Direction_Both]


@dataclass
class Scrollable:
    content: shared.Element
    width: Optional[length.Length]
    height: Optional[length.Length]
    on_scroll: Optional[int]
    direction: Optional[Direction]
