# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import shared
from ..imports import length

class Anchor(Enum):
    """
    The anchor of the scroller of a scrollable relative to its viewport.
    """
    START = 0
    END = 1

@dataclass
class Scrollbar:
    width: Optional[float]
    margin: Optional[float]
    scroller_width: Optional[float]
    anchor: Optional[Anchor]
    spacing: Optional[float]


@dataclass
class Direction_Vertical:
    value: Scrollbar


@dataclass
class Direction_Horizontal:
    value: Scrollbar


@dataclass
class Direction_Both:
    value: Tuple[Scrollbar, Scrollbar]


Direction = Union[Direction_Vertical, Direction_Horizontal, Direction_Both]


class Scrollable:
    
    def __init__(self, content: shared.Element) -> None:
        raise NotImplementedError

    def width(self, w: length.Length) -> None:
        raise NotImplementedError
    def height(self, h: length.Length) -> None:
        raise NotImplementedError
    def direction(self, d: Direction) -> None:
        raise NotImplementedError
    def on_scroll(self, mapper: int) -> None:
        raise NotImplementedError
    @classmethod
    def into_element(cls, widget: Self) -> shared.Element:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



