# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


@dataclass
class Color:
    """
    A color in the sRGB color space.
    """
    r: float
    g: float
    b: float
    a: float

class Element:
    """
    The base element resource for UI widgets.
    Note: The dummy function is required for jco componentize to generate the class.
    See: https://github.com/bytecodealliance/ComponentizeJS/issues/221
    """
    
    def noop(self) -> None:
        """
        Dummy function to trigger class generation in jco componentize.
        """
        raise NotImplementedError
    def explain(self, color: Color) -> Self:
        """
        Wraps the element with a debug overlay of the given color.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class ContentFit(Enum):
    CONTAIN = 0
    COVER = 1
    FILL = 2
    NONE = 3
    SCALE_DOWN = 4

class FilterMethod(Enum):
    LINEAR = 0
    NEAREST = 1


@dataclass
class Rotation_Floating:
    value: float


@dataclass
class Rotation_Solid:
    value: float


Rotation = Union[Rotation_Floating, Rotation_Solid]



