# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import length


@dataclass
class Slider:
    """
    A horizontal bar for selecting a value from a range of floats.
    """

    range_start: float
    range_end: float
    value: float
    on_change: int
    default: Optional[float]
    on_release: Optional[int]
    width: Optional[length.Length]
    height: Optional[float]
    step: Optional[float]
    shift_step: Optional[float]
