# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import length
from ..imports import shared

class Slider:
    """
    A horizontal bar for selecting a value from a range of floats.
    """
    
    def __init__(self, range_start: float, range_end: float, value: float, on_change: int) -> None:
        raise NotImplementedError

    def default(self, v: float) -> None:
        raise NotImplementedError
    def on_release(self, msg: int) -> None:
        raise NotImplementedError
    def width(self, w: length.Length) -> None:
        raise NotImplementedError
    def height(self, h: float) -> None:
        raise NotImplementedError
    def step(self, s: float) -> None:
        raise NotImplementedError
    def shift_step(self, s: float) -> None:
        raise NotImplementedError
    @classmethod
    def into_element(cls, widget: Self) -> shared.Element:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



