# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import length
from ..imports import shared


@dataclass
class Table:
    """
    A grid-like visual representation of data distributed in columns and rows.
    """

    columns: List[shared.Element]
    rows: List[shared.Element]
    width: Optional[length.Length]
    padding: Optional[float]
    padding_x: Optional[float]
    padding_y: Optional[float]
    separator: Optional[float]
    separator_x: Optional[float]
    separator_y: Optional[float]
