# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import shared
from ..imports import length
from ..imports import alignment
from ..imports import text
from ..imports import padding

class TextInput:
    """
    A field that can be filled with text.
    """
    
    def __init__(self, placeholder: str, value: str) -> None:
        raise NotImplementedError

    def secure(self, secure: bool) -> None:
        raise NotImplementedError
    def on_input(self, mapper: int) -> None:
        raise NotImplementedError
    def on_submit(self, msg: int) -> None:
        raise NotImplementedError
    def on_paste(self, mapper: int) -> None:
        raise NotImplementedError
    def width(self, w: length.Length) -> None:
        raise NotImplementedError
    def padding(self, p: padding.Padding) -> None:
        raise NotImplementedError
    def size(self, s: float) -> None:
        raise NotImplementedError
    def line_height(self, lh: text.LineHeight) -> None:
        raise NotImplementedError
    def align_x(self, a: alignment.Horizontal) -> None:
        raise NotImplementedError
    @classmethod
    def into_element(cls, widget: Self) -> shared.Element:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



