# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import shared
from ..imports import length
from ..imports import alignment


@dataclass
class TextAlignment_Default:
    pass


@dataclass
class TextAlignment_Left:
    pass


@dataclass
class TextAlignment_Center:
    pass


@dataclass
class TextAlignment_Right:
    pass


@dataclass
class TextAlignment_Justified:
    pass


TextAlignment = Union[TextAlignment_Default, TextAlignment_Left, TextAlignment_Center, TextAlignment_Right, TextAlignment_Justified]



@dataclass
class LineHeight_Relative:
    value: float


@dataclass
class LineHeight_Absolute:
    value: float


LineHeight = Union[LineHeight_Relative, LineHeight_Absolute]


class Shaping(Enum):
    BASIC = 0
    ADVANCED = 1
    AUTO = 2

class Wrapping(Enum):
    NONE = 0
    WORD = 1
    GLYPH = 2
    WORD_OR_GLYPH = 3

class Text:
    
    def __init__(self, content: str) -> None:
        raise NotImplementedError

    def size(self, s: float) -> None:
        raise NotImplementedError
    def line_height(self, lh: LineHeight) -> None:
        raise NotImplementedError
    def width(self, w: length.Length) -> None:
        raise NotImplementedError
    def height(self, h: length.Length) -> None:
        raise NotImplementedError
    def center(self) -> None:
        raise NotImplementedError
    def align_x(self, align: TextAlignment) -> None:
        raise NotImplementedError
    def align_y(self, align: alignment.Vertical) -> None:
        raise NotImplementedError
    def color(self, c: shared.Color) -> None:
        raise NotImplementedError
    @classmethod
    def into_element(cls, widget: Self) -> shared.Element:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



