# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import shared


class Position(Enum):
    TOP = 0
    BOTTOM = 1
    LEFT = 2
    RIGHT = 3
    FOLLOW_CURSOR = 4


@dataclass
class Tooltip:
    content: shared.Element
    tooltip: shared.Element
    position: Position
    gap: Optional[float]
    padding: Optional[float]
    snap_within_viewport: Optional[bool]
