use wasmtime::component::bindgen;

bindgen!({
    path: "wit",
    with: {
        "iced:app/shared.element": crate::widgets::Element,
        "iced:app/text.text": crate::widgets::text::TextResource,
        "iced:app/column.column": crate::widgets::column::ColumnResource,
        "iced:app/row.row": crate::widgets::row::RowResource,
        "iced:app/container.container": crate::widgets::container::ContainerResource,
        "iced:app/tooltip.tooltip": crate::widgets::tooltip::TooltipResource,
        "iced:app/button.button": crate::widgets::button::ButtonResource,
        "iced:app/rule.rule": crate::widgets::rule::RuleResource,
        "iced:app/space.space": crate::widgets::space::SpaceResource,
        "iced:app/svg.svg": crate::widgets::svg::SvgResource,
        "iced:app/image.image": crate::widgets::image::ImageResource,
        "iced:app/progress-bar.progress-bar": crate::widgets::progress_bar::ProgressBarResource,
        "iced:app/radio.radio": crate::widgets::radio::RadioResource,
        "iced:app/checkbox.checkbox": crate::widgets::checkbox::CheckboxResource,
        "iced:app/toggler.toggler": crate::widgets::toggler::TogglerResource,
        "iced:app/text-input.text-input": crate::widgets::text_input::TextInputResource,
        "iced:app/slider.slider": crate::widgets::slider::SliderResource,
        "iced:app/vertical-slider.vertical-slider": crate::widgets::vertical_slider::VerticalSliderResource,
        "iced:app/combo-box.combo-box": crate::widgets::combo_box::ComboBoxResource,
        "iced:app/pick-list.pick-list": crate::widgets::pick_list::PickListResource,
        "iced:app/markdown.markdown": crate::widgets::markdown::MarkdownResource,
        "iced:app/float.float": crate::widgets::float::FloatResource,
        "iced:app/grid.grid": crate::widgets::grid::GridResource,
        "iced:app/keyed.keyed-column": crate::widgets::keyed::KeyedColumnResource,
        "iced:app/scrollable.scrollable": crate::widgets::scrollable::ScrollableResource,
    },
});
